// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnylrvasulkxwbjzzzpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhueWxydmFzdWxreHdianp6enBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDMyMjAsImV4cCI6MjA2NTU3OTIyMH0.NX2gGpyZgu1Y4Pp3S1lm75VJABA7WDwrXejv_2BKT0I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);